### ISSUE TITLE
moveit_msgs/GraspPlanning.h: No such file or directory

### ISSUE THREAD

**Issue by jackros1022** [Jntzko/tams_ur5_pick_place#5]
fatal error: moveit_msgs/GraspPlanning.h: No such file or directory
 #include <moveit_msgs/GraspPlanning.h>
                                       ^
compilation terminated.

**I have installed ros-indigo-moveit-msgs,but it still appear error.**

Any hints would be appreciated.

**Comment by Jntzko** [comment]
You have to checkout the indigo-devel branch from this repo:
https://github.com/ros-planning/moveit_msgs.git

and probably the indigo-devel branch from:
https://github.com/ros-planning/moveit.git

I hope this will help ;)
